/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JOptionPane;
import Controlador.Main;

/**
 *
 * @author alumno
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.Ocultar();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void Ocultar() {  
        lblTitulo.setVisible(false);
        jpanPanel.setVisible(false);
        txtConclusion.setVisible(false);
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        lblTitulo = new javax.swing.JLabel();
        txtConclusion = new javax.swing.JTextArea();
        jpanPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabla = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmNuevoLibro = new javax.swing.JMenuItem();
        lmmodLibro = new javax.swing.JMenuItem();
        jmEliminarLibro = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmNuevaRevista = new javax.swing.JMenuItem();
        jmModRevista = new javax.swing.JMenuItem();
        jmEliminarRevista = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jmListaLibros = new javax.swing.JMenuItem();
        jmStockInter = new javax.swing.JMenuItem();
        jmLibrosPrecioMayorA = new javax.swing.JMenuItem();
        jmPorcentajeInter = new javax.swing.JMenuItem();
        jmPromedioNacionales = new javax.swing.JMenuItem();
        jmLibromasCostoso = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenu3 = new javax.swing.JMenu();
        jmListadeRevistas = new javax.swing.JMenuItem();
        jmStockOcio = new javax.swing.JMenuItem();
        jmRevExpprecioMayorA = new javax.swing.JMenuItem();
        jmPorcentajeRev = new javax.swing.JMenuItem();
        jmPromRev = new javax.swing.JMenuItem();
        jmRevmasCostosa = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Titulo");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 530, -1));

        txtConclusion.setColumns(20);
        txtConclusion.setRows(5);
        getContentPane().add(txtConclusion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 550, -1));

        jpanPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTabla.getTableHeader().setResizingAllowed(false);
        tblTabla.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblTabla);

        jpanPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 530, -1));

        getContentPane().add(jpanPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 550, 440));

        jMenuBar1.setBackground(new java.awt.Color(204, 255, 204));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuBar1.setForeground(new java.awt.Color(204, 204, 255));

        jMenu1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu1.setText("A-B-M");

        jmNuevoLibro.setText("Cargar Libro");
        jmNuevoLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmNuevoLibroActionPerformed(evt);
            }
        });
        jMenu1.add(jmNuevoLibro);

        lmmodLibro.setText("Modificar Libro");
        lmmodLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lmmodLibroActionPerformed(evt);
            }
        });
        jMenu1.add(lmmodLibro);

        jmEliminarLibro.setText("Eliminar Libro");
        jMenu1.add(jmEliminarLibro);
        jMenu1.add(jSeparator1);

        jmNuevaRevista.setText("Nueva Revista");
        jMenu1.add(jmNuevaRevista);

        jmModRevista.setText("Modificar Revista");
        jMenu1.add(jmModRevista);

        jmEliminarRevista.setText("Eliminar Revista");
        jMenu1.add(jmEliminarRevista);

        jMenuBar1.add(jMenu1);

        jMenu4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu4.setText("Consultas");

        jMenu2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu2.setText("Consultas Libros");

        jmListaLibros.setText("Lista de Libros");
        jmListaLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmListaLibrosActionPerformed(evt);
            }
        });
        jMenu2.add(jmListaLibros);

        jmStockInter.setText("Stock Libros Internacionales");
        jmStockInter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmStockInterActionPerformed(evt);
            }
        });
        jMenu2.add(jmStockInter);

        jmLibrosPrecioMayorA.setText("Libros Nacionales con Precio Mayor a:");
        jmLibrosPrecioMayorA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmLibrosPrecioMayorAActionPerformed(evt);
            }
        });
        jMenu2.add(jmLibrosPrecioMayorA);

        jmPorcentajeInter.setText("Porcentaje de Libros ");
        jmPorcentajeInter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmPorcentajeInterActionPerformed(evt);
            }
        });
        jMenu2.add(jmPorcentajeInter);

        jmPromedioNacionales.setText("Precio Promedio Libros Nacionales");
        jmPromedioNacionales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmPromedioNacionalesActionPerformed(evt);
            }
        });
        jMenu2.add(jmPromedioNacionales);

        jmLibromasCostoso.setText("Libro Nacional Mas Costoso");
        jmLibromasCostoso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmLibromasCostosoActionPerformed(evt);
            }
        });
        jMenu2.add(jmLibromasCostoso);

        jMenu4.add(jMenu2);
        jMenu4.add(jSeparator3);

        jMenu3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu3.setText("Consultas Revistas");

        jmListadeRevistas.setText("Lista de Revistas");
        jmListadeRevistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmListadeRevistasActionPerformed(evt);
            }
        });
        jMenu3.add(jmListadeRevistas);

        jmStockOcio.setText("Stock Revistas de Ocio");
        jmStockOcio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmStockOcioActionPerformed(evt);
            }
        });
        jMenu3.add(jmStockOcio);

        jmRevExpprecioMayorA.setText("Revistas Esp. con precio mayor a :");
        jmRevExpprecioMayorA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmRevExpprecioMayorAActionPerformed(evt);
            }
        });
        jMenu3.add(jmRevExpprecioMayorA);

        jmPorcentajeRev.setText("Porcentaje Revistas");
        jmPorcentajeRev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmPorcentajeRevActionPerformed(evt);
            }
        });
        jMenu3.add(jmPorcentajeRev);

        jmPromRev.setText("Precio Promedio de Revistas de Ocio");
        jmPromRev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmPromRevActionPerformed(evt);
            }
        });
        jMenu3.add(jmPromRev);

        jmRevmasCostosa.setText("Revista mas Costosa");
        jmRevmasCostosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmRevmasCostosaActionPerformed(evt);
            }
        });
        jMenu3.add(jmRevmasCostosa);

        jMenu4.add(jMenu3);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmNuevoLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmNuevoLibroActionPerformed
        this.Ocultar();
        new AltaLibros().setVisible(true);
    }//GEN-LAST:event_jmNuevoLibroActionPerformed

    private void lmmodLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lmmodLibroActionPerformed
        this.Ocultar();
// TODO add your handling code here:
    }//GEN-LAST:event_lmmodLibroActionPerformed

    private void jmLibrosPrecioMayorAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmLibrosPrecioMayorAActionPerformed
        this.Ocultar();
        double aux= Double.parseDouble(JOptionPane.showInputDialog(null, "Ingrese Precio"));
        tblTabla.setModel(new javax.swing.table.DefaultTableModel(
            Main.lista.LibrosNacionalesPrecioMayorA(aux),
            new String [] {
                "Codigo", "Descripcion", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTabla.getTableHeader().setReorderingAllowed(false);
        lblTitulo.setText("Libros Nacionales con precio mayor a: $"+String.format("%.2f", aux));
        lblTitulo.setVisible(true);
        jpanPanel.setVisible(true);
        
    }//GEN-LAST:event_jmLibrosPrecioMayorAActionPerformed

    private void jmPorcentajeInterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmPorcentajeInterActionPerformed
        this.Ocultar();
        lblTitulo.setText("Porcentaje de Libros");
        lblTitulo.setVisible(true);
        txtConclusion.setText("Porcentaje de Libros Internacionales :"+String.format("%.2f", Main.lista.PorcentajeLibrosInternacionales())+"%"
                            +"\nPorcentaje de Libros Internacionales :"+String.format("%.2f",100- Main.lista.PorcentajeLibrosInternacionales())+"%");
        txtConclusion.setVisible(true);
    }//GEN-LAST:event_jmPorcentajeInterActionPerformed

    private void jmPromedioNacionalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmPromedioNacionalesActionPerformed
        this.Ocultar();
        lblTitulo.setText("Precio Promedio Libros Nacionales");
        lblTitulo.setVisible(true);
        txtConclusion.setText("El Precio Promedio de los Libros Nacionales es de: $"+String.format("%.2f", Main.lista.PromedioNacionales()));
        txtConclusion.setVisible(true);
        
// TODO add your handling code here:
    }//GEN-LAST:event_jmPromedioNacionalesActionPerformed

    private void jmPorcentajeRevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmPorcentajeRevActionPerformed
        this.Ocultar();
        this.Ocultar();
        lblTitulo.setText("Porcentaje de Revistas");
        lblTitulo.setVisible(true);
        txtConclusion.setText("Porcentaje de Revistas de Ocio: "+String.format("%.2f", Main.lista.PorcentajeRevOcio())+"%"
                            +"\nPorcentaje de Revistas Especializadas: "+String.format("%.2f",100- Main.lista.PorcentajeRevOcio())+"%");
        txtConclusion.setVisible(true);
    }//GEN-LAST:event_jmPorcentajeRevActionPerformed

    private void jmPromRevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmPromRevActionPerformed
        this.Ocultar();
        this.Ocultar();
        lblTitulo.setText("Precio Promedio Revistas de Ocio");
        lblTitulo.setVisible(true);
        txtConclusion.setText("El Precio Promedio de las Revistas de Ocio es de: $"+String.format("%.2f", Main.lista.PromedioOcio()));
        txtConclusion.setVisible(true);
    }//GEN-LAST:event_jmPromRevActionPerformed

    private void jmRevmasCostosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmRevmasCostosaActionPerformed
        this.Ocultar();
        lblTitulo.setText("Revista Mas Costosa");
        lblTitulo.setVisible(true);
        txtConclusion.setText(Main.lista.RevistaMasCostosa());
        txtConclusion.setVisible(true);
    }//GEN-LAST:event_jmRevmasCostosaActionPerformed

    private void jmListaLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmListaLibrosActionPerformed
        tblTabla.setModel(new javax.swing.table.DefaultTableModel(
                Main.lista.ListaPreciosLibro(),
                new String[]{
                    "Codigo", "Descripcion", "Precio"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                false, false, false
            };
            
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        tblTabla.getTableHeader().setReorderingAllowed(false);
        
        lblTitulo.setText("Lista de Libros");
        lblTitulo.setVisible(true);
        jpanPanel.setVisible(true);
        
    }//GEN-LAST:event_jmListaLibrosActionPerformed

    private void jmStockInterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmStockInterActionPerformed
        this.Ocultar();
        tblTabla.setModel(new javax.swing.table.DefaultTableModel(
            Main.lista.StockInternacionales(),
            new String [] {
                "Codigo", "Descripcion", "Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTabla.getTableHeader().setReorderingAllowed(false);
        lblTitulo.setText("Stock de Libros Internacionales");
        lblTitulo.setVisible(true);
        jpanPanel.setVisible(true);
                
        
    }//GEN-LAST:event_jmStockInterActionPerformed

    private void jmLibromasCostosoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmLibromasCostosoActionPerformed
        this.Ocultar();
        lblTitulo.setText("Libro Nacional Mas Costoso");
        lblTitulo.setVisible(true);
        txtConclusion.setText(Main.lista.NacionalMasCostoso());
        txtConclusion.setVisible(true);
    }//GEN-LAST:event_jmLibromasCostosoActionPerformed

    private void jmListadeRevistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmListadeRevistasActionPerformed
        this.Ocultar();
        tblTabla.setModel(new javax.swing.table.DefaultTableModel(
                Main.lista.ListaPrecioRevista(),
                new String[]{
                    "Codigo", "Nombre", "Precio"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                false, false, false
            };
            
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        tblTabla.getTableHeader().setReorderingAllowed(false);
        
        lblTitulo.setText("Lista de Revistas");
        lblTitulo.setVisible(true);
        jpanPanel.setVisible(true);        
        
    }//GEN-LAST:event_jmListadeRevistasActionPerformed

    private void jmStockOcioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmStockOcioActionPerformed
        this.Ocultar();
        tblTabla.setModel(new javax.swing.table.DefaultTableModel(
            Main.lista.StockOcio(),
            new String [] {
                "Codigo", "Nombre", "Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTabla.getTableHeader().setReorderingAllowed(false);
        lblTitulo.setText("Stock de Revistas de Ocio");
        lblTitulo.setVisible(true);
        jpanPanel.setVisible(true);
    }//GEN-LAST:event_jmStockOcioActionPerformed

    private void jmRevExpprecioMayorAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmRevExpprecioMayorAActionPerformed
        this.Ocultar();
        double precio= Double.parseDouble(JOptionPane.showInputDialog(null, "Ingrese Precio"));
        tblTabla.setModel(new javax.swing.table.DefaultTableModel(
            Main.lista.RevistasPrecioMayorA(precio),
            new String [] {
                "Codigo", "Descripcion", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTabla.getTableHeader().setReorderingAllowed(false);
        lblTitulo.setText("Revistas Especializadas con precio mayor a: $"+String.format("%.2f", precio));
        lblTitulo.setVisible(true);
        jpanPanel.setVisible(true);
    }//GEN-LAST:event_jmRevExpprecioMayorAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenuItem jmEliminarLibro;
    private javax.swing.JMenuItem jmEliminarRevista;
    private javax.swing.JMenuItem jmLibromasCostoso;
    private javax.swing.JMenuItem jmLibrosPrecioMayorA;
    private javax.swing.JMenuItem jmListaLibros;
    private javax.swing.JMenuItem jmListadeRevistas;
    private javax.swing.JMenuItem jmModRevista;
    private javax.swing.JMenuItem jmNuevaRevista;
    private javax.swing.JMenuItem jmNuevoLibro;
    private javax.swing.JMenuItem jmPorcentajeInter;
    private javax.swing.JMenuItem jmPorcentajeRev;
    private javax.swing.JMenuItem jmPromRev;
    private javax.swing.JMenuItem jmPromedioNacionales;
    private javax.swing.JMenuItem jmRevExpprecioMayorA;
    private javax.swing.JMenuItem jmRevmasCostosa;
    private javax.swing.JMenuItem jmStockInter;
    private javax.swing.JMenuItem jmStockOcio;
    private javax.swing.JPanel jpanPanel;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JMenuItem lmmodLibro;
    private javax.swing.JTable tblTabla;
    private javax.swing.JTextArea txtConclusion;
    // End of variables declaration//GEN-END:variables
}
